# Generated by Django 4.0.7 on 2022-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_code', models.PositiveSmallIntegerField(default=840)),
                ('to_code', models.PositiveSmallIntegerField(default=980)),
                ('rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_id', models.PositiveSmallIntegerField(db_index=True)),
                ('order_id', models.CharField(db_index=True, max_length=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=9)),
                ('delivery_date', models.DateField()),
                ('msg_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('excel_id',),
            },
        ),
    ]
