# Generated by Django 4.0.7 on 2022-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets_extraction_app', '0002_order_msg_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='msg_status_text',
            field=models.CharField(default='Expired', max_length=20),
        ),
    ]
