# Generated by Django 4.0.7 on 2022-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets_extraction_app', '0003_alter_order_msg_status_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='date_of_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='msg_status_text',
            field=models.CharField(default='In_process', max_length=20),
        ),
    ]
