# Generated by Django 4.0.7 on 2022-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets_extraction_app', '0004_exchangerate_date_of_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='date_of_rate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
