# Generated by Django 4.0.7 on 2022-08-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets_extraction_app', '0005_alter_exchangerate_date_of_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='msg_status_text',
            field=models.CharField(default='In_process...', max_length=20),
        ),
    ]
